export const images = [
  {
    src: require("./cow.jpeg"),
    width: 2923,
    height: 2897,
    keywords: ["cow", "animal"],
  },
  {
    src: require("./bear.jpeg"),
    width: 1609,
    height: 2010,
    keywords: ["bear", "animal", "dog", "lab", "black lab"],
  },
  {
    src: require("./bug.jpeg"),
    width: 3158,
    height: 2277,
    keywords: ["volkswagen", "bug", "car"],
  },
  {
    src: require("./autumn.jpeg"),
    width: 3580,
    height: 2887,
    keywords: ["autumn", "fall", "leaves", "water", "psychedelic"],
  },
  {
    src: require("./cliffs.jpeg"),
    width: 2818,
    height: 3590,
    keywords: ["cliff", "water", "waterfall"],
  },
  {
    src: require("./coriolis.jpeg"),
    width: 2833,
    height: 2865,
    keywords: [
      "coriolis",
      "earth",
      "space",
      "moon",
      "galaxy",
      "galactic",
      "universe",
      "weather",
    ],
  },
  {
    src: require("./universe.jpeg"),
    width: 2899,
    height: 3890,
    keywords: [
      "earth",
      "saturn",
      "sunset",
      "sun",
      "space",
      "moon",
      "galaxy",
      "galactic",
      "universe",
      "weather",
    ],
  },
  {
    src: require("./butterfly.jpeg"),
    width: 2690,
    height: 3763,
    keywords: ["butterfly", "animal", "insect", "hummingbird", "bird"],
  },
  {
    src: require("./octopus.jpeg"),
    width: 2790,
    height: 2834,
    keywords: [
      "octopus",
      "animal",
      "sea",
      "ocean",
      "aquatic",
      "underwater",
      "water",
    ],
  },
  {
    src: require("./spiderman.jpeg"),
    width: 2850,
    height: 3809,
    keywords: [
      "spiderman",
      "spider",
      "man",
      "hero",
      "super",
      "superhero",
      "new york",
      "city",
    ],
  },
  {
    src: require("./choices.jpeg"),
    width: 3904,
    height: 1289,
    keywords: [
      "make",
      "reasonable",
      "choices",
      "night",
      "sea",
      "ocean",
      "water",
      "dark",
      "stars",
    ],
  },
  {
    src: require("./spongebob.jpeg"),
    width: 3538,
    height: 2833,
    keywords: [
      "spongebob",
      "music",
      "microphone",
      "sing",
      "rock",
      "band",
      "concert",
      "festival",
      "laser",
      "light",
      "stadium",
    ],
  },
  {
    src: require("./beach.jpeg"),
    width: 1366,
    height: 1024,
    keywords: [
      "beach",
      "sea",
      "ocean",
      "house",
      "beach house",
      "ball",
      "chair",
      "sand",
      "umbrella",
      "building",
    ],
  },
  {
    src: require("./louisville.jpeg"),
    width: 3908,
    height: 1285,
    keywords: [
      "lousiville",
      "kentucky",
      "skyline",
      "sun",
      "light",
      "sunset",
      "stadium",
    ],
  },
  {
    src: require("./monument.jpeg"),
    width: 1302,
    height: 3959,
    keywords: [
      "monument",
      "DC",
      "Washington",
      "night",
      "dark",
      "light",
      "pencil",
      "brick",
      "building",
    ],
  },
  {
    src: require("./poppies.jpeg"),
    width: 2063,
    height: 1536,
    keywords: ["poppies", "flowers", "field"],
  },
  {
    src: require("./wintersun.jpeg"),
    width: 3885,
    height: 1459,
    keywords: ["winter", "cold", "snow", "trees", "sun", "sunset"],
  },
  {
    src: require("./rg3.jpeg"),
    width: 2877,
    height: 3590,
    keywords: [
      "rg3",
      "football",
      "player",
      "football player",
      "redskins",
      "washington",
      "DC",
      "FedEx",
    ],
  },
  {
    src: require("./urinal.jpeg"),
    width: 3605,
    height: 2873,
    keywords: ["urinal", "bathroom", "pee", "urine"],
  },
  {
    src: require("./geofish.jpeg"),
    width: 3845,
    height: 2872,
    keywords: ["geofish", "geometry", "fish", "squares"],
  },
  {
    src: require("./objects.jpeg"),
    width: 3754,
    height: 2776,
    keywords: ["objects"],
  },
  {
    src: require("./shapes.jpeg"),
    width: 2050,
    height: 1534,
    keywords: ["shapes"],
  },
  {
    src: require("./dogbike.jpeg"),
    width: 2688,
    height: 3902,
    keywords: ["dog", "lab", "black lab", "animal", "bike", "bicycle"],
  },
  {
    src: require("./brothers.jpeg"),
    width: 3850,
    height: 2898,
    keywords: [
      "brothers",
      "family",
      "hockey",
      "andrew",
      "daniel",
      "aj",
      "brotherhood",
    ],
  },
  {
    src: require("./coat.jpeg"),
    width: 3467,
    height: 2893,
    keywords: ["coat", "jacket", "clothes", "cold", "winter"],
  },
  {
    src: require("./stretch.jpeg"),
    width: 2036,
    height: 1836,
    keywords: ["stretch", "shoe"],
  },
  {
    src: require("./virginia.jpeg"),
    width: 3851,
    height: 2347,
    keywords: ["virginia", "uva", "shoe", "shirt"],
  },
  {
    src: require("./back.jpeg"),
    width: 3669,
    height: 2924,
    keywords: ["back", "tree", "leaves", "leaf", "run", "running", "runner"],
  },
  {
    src: require("./nightrace.jpeg"),
    width: 2465,
    height: 3949,
    keywords: [
      "night",
      "dark",
      "race",
      "herndon",
      "run",
      "running",
      "runner",
      "track",
    ],
  },
  {
    src: require("./partners.jpeg"),
    width: 2017,
    height: 2049,
    keywords: [
      "run",
      "running",
      "runner",
      "relay",
      "partners",
      "4x4",
      "sprint",
      "baton",
    ],
  },
  {
    src: require("./finishline.jpeg"),
    width: 2745,
    height: 3896,
    keywords: [
      "run",
      "running",
      "runner",
      "track",
      "herndon",
      "finish line",
      "finish",
      "sprint",
    ],
  },
  {
    src: require("./prerace.jpeg"),
    width: 2058,
    height: 1536,
    keywords: [
      "run",
      "running",
      "runner",
      "herndon",
      "jersey",
      "number",
      "track",
    ],
  },
  {
    src: require("./hand.jpeg"),
    width: 2807,
    height: 2394,
    keywords: ["run", "running", "runner", "hand", "watch"],
  },
  {
    src: require("./spike.jpeg"),
    width: 2134,
    height: 1536,
    keywords: ["run", "running", "runner", "shoe", "spike", "race", "sprint"],
  },
  {
    src: require("./snowshoe.jpeg"),
    width: 1954,
    height: 2048,
    keywords: ["run", "running", "runner", "snow", "shoe", "winter", "cold"],
  },
  {
    src: require("./uphill.jpeg"),
    width: 2574,
    height: 1536,
    keywords: [
      "run",
      "running",
      "runner",
      "cone",
      "grass",
      "field",
      "hill",
      "uphill",
      "shoe",
      "spike",
    ],
  },
  {
    src: require("./muddyshoe.jpeg"),
    width: 2199,
    height: 1536,
    keywords: [
      "mud",
      "dirt",
      "leg",
      "shoe",
      "run",
      "running",
      "runner",
      "trail",
    ],
  },
  {
    src: require("./blueshoe.jpeg"),
    width: 2468,
    height: 1536,
    keywords: [
      "run",
      "running",
      "runner",
      "shoe",
      "track",
      "train",
      "shoelace",
    ],
  },
  {
    src: require("./hawk.jpeg"),
    width: 2475,
    height: 2486,
    keywords: ["herndon", "hawk", "bird", "animal", "wings"],
  },
  {
    src: require("./spongebobs.jpeg"),
    width: 2100,
    height: 1536,
    keywords: ["spongebob"],
  },
  {
    src: require("./snowmen.jpeg"),
    width: 2864,
    height: 1520,
    keywords: [
      "snowmen",
      "snowman",
      "cold",
      "winter",
      "snow",
      "holiday",
      "christmas",
      "tree",
    ],
  },
];
